### ISSUE TITLE
Informasjonen om hvordan endre team for en applikasjon må oppdateres

### ISSUE THREAD

**Issue by mortenlj** [nais/doc#101]
Etter at vi innførte team namespaces så er informasjonen på https://doc.nais.io/deployment/change-team mangelfull.

Vi må oppdatere med hva som trengs for å flytte en app fra et namespace til et annet.

**Comment by Kyrremann** [comment]
Er vel mye av det samme, bortsett fra at man må endre github-team og namespace også.

**Comment by x10an14** [comment]
Dette ser relevant ut, om noen (jeg skal lete selv altså) klarer å finne det igjen i nåværende versjon: https://github.com/nais/doc/issues/47#issuecomment-550238951

**Comment by Kyrremann** [comment]
Den Morten lenker til er jeg ganske sikker på er i nåværende form/versjon av det Vegar lenket til.

**Comment by x10an14** [comment]
Selv-innsikt: Å innse at man ikke får prioritert enn oppgave man har påtatt seg...
