### ISSUE TITLE
Site analytics

### ISSUE THREAD

**Issue by chinatsu** [nais/doc#140]
With the introduction of a documentation stack that allows for more fine grained control, I think it would be quite useful to add some sort of analytics tool (I suppose there was already support for this in GitBooks too? I don't know). I'm especially thinking about the case that page views can be counted; with such data can work be done to put the more viewed pages closer to the reader and thus (hopefully) improve the quality of life for those who wish to read the more important pages.

There exists [documentation on how to set up analytics](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics) where the path of least resistance is certainly Google Analytics, though there's also a set of instructions on how one would implement alternative services (I'm thinking Amplitude, since there exists some organisational license).

**Comment by Kyrremann** [comment]
Tror Amplitude er et godt valg. Tror som organisasjon så prøver vi å gå vekk fra Google Analytics. Amplitude-gjengen kan nok hjelpe oss. Siden vi ikke kjører på plattformen, så kan det hende vi må gjøre noe ekstra.
