### ISSUE TITLE
Separating on-prem and GCP documentation

### ISSUE THREAD

**Issue by chinatsu** [nais/doc#141]
It came up in a discussion between @x10an14, @Kyrremann, @gorzan, and I, that it seems reasonable to split documentation regarding on-prem and GCP in separate parts. 

First and foremost, this would help tidy up the connections between different parts of NAIS (at least, when it comes to GCP and on-prem 🙃 ) as certain things specific to one or the other currently have their most natural location in other categories. Thus, the current setup can be a little bewildering since one might see a thing in another category and think "hey, that's a cool technology!" only to find it is only supported in a Kubernetes cluster that the reader isn't using.

I'm certain there are problem spots with this kind of setup, since the two kinds of clusters share a fair bit of info. It might lead to needing some duplicate info between the two categories, or a third main category that collects the shared stuff, neither of these are particularly desirable ideas. 
Still, I do feel as if it could be beneficial for the reader if this is done with care.

**Comment by audunstrand** [comment]
There are quite a lot of Nais that is common across on-prem and cloud. 

I think we should do what helps migration.

**Comment by tronghn** [comment]
Perhaps a passthrough and separation of on-prem-only related documentation to its own category (e.g. Legacy or similar) would be beneficial here?

**Comment by chinatsu** [comment]
i've got similar ideas @tronghn. it does feel as if on-prem is discouraged if there is a choice, and so the focus should be on the cool new stuff without the stuff that's not cool mixed in. 

one has the opportunity to point to the same pages in several different categories, like
```
- gcp:
    - page about something common
    - page about something gcp 
- on-prem:
    - page about something common
    - page about something on-prem
```

however, if the reader wants to read about the page about something common in the on-prem category, the navigation finds the first occurrence of that page in the tree and marks that one as active :(

**Comment by Kyrremann** [comment]
Jeg ser for meg at vi presenterer doc-en med hvordan vi tenker at fremtids NAIS er, og da er alt som er spesifikt for on-prem legacy, og det kan være under en egen side sammen med openAM.

**Comment by Kyrremann** [comment]
Dette ble delvist løst med legacy, og egne info-bokser for on-prem og gcp.
