### ISSUE TITLE
Tydeliggjøre at intern.nav.no er tilgjengelig fra vdi

### ISSUE THREAD

**Issue by havstein** [nais/doc#172]
Informasjonen i [on-premises.md](https://github.com/nais/doc/blob/master/docs/clusters/on-premises.md) (https://doc.nais.io/clusters/on-premises/) om ingresser/domener ser bra ut, men det kan kanskje tydeliggjøres at intern.nav.no _også_ kan nås fra vdi? "accessible from"-kolonnen sier bare naisdevice.

<img width="845" alt="image" src="https://user-images.githubusercontent.com/136872/110130704-9bc1cd00-7dc9-11eb-9c3e-e25e92ebb762.png">

**Comment by Kyrremann** [comment]
Har ikke sjekket selv, men hvis du har, så kan jeg/du bare lage en PR med fix!
