### ISSUE TITLE
Skrive script for å hel-automatisere midlertidig aksess til GCP DB

### ISSUE THREAD

**Issue by x10an14** [nais/doc#180]
Ref: https://nav-it.slack.com/archives/C0190SV7KSN/p1618828834187100?thread_ts=1618822735.174400&cid=C0190SV7KSN

Kan sees på i sammenheng med #179

**Comment by Muni10** [comment]
Denne er vel ok i og med at vi tilbyr connection via nais cli. Lukker.

**Comment by Kyrremann** [comment]
Løst med eget flag i nais-cli: https://docs.nais.io/cli/commands/postgres/#prepare
