### ISSUE TITLE
Forbedre beskrivelse av bruk av labels i alerts

### ISSUE THREAD

**Issue by ahusby** [nais/doc#223]
Jeg skulle ønske at dokumentasjonen om alerts https://doc.nais.io/observability/alerts/#expressive-descriptions-or-actions forklarte bedre hvordan jeg kan vite hvilke labels jeg har tilgjengelig. Jeg ser hvordan jeg kan referere til en label, men hvordan vet jeg om en label eksisterer? Hvor kommer labels fra? 

Grunnen til at jeg begynte å tenke på dette er at mitt team har hatt alerts i Slack hvor det ikke står hvilken app som er opphavet til alerten. Det ble slik fordi alerten hadde severity warning, og vi hadde basert oss på å bruke prependText https://doc.nais.io/observability/alerts/reference/#receiversslackprependtext til å hardkode appnavnet der. Jeg oppdaget da at prependText bare brukes for alerts med severity danger.

Vi hadde definert en alert som var definert med ` action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det forekommer warnings"
`.
Da denne førte til en melding i Slack sto det ingenting istedenfor {{ $labels.log_app }} og {{ $labels.log_namespace }}

**Comment by Kyrremann** [comment]
Du ser hvilke labels som er tilgjengelig ved å kjøre `expr` din og se hva som er tilgjengelig der.
https://doc.nais.io/observability/alerts/#writing-the-expr

Jeg kan legge til eksplisitt tekst om dette.

**Comment by ahusby** [comment]
Takk. Det du sier der er omtrent det som står i doc-en, og det har ikke vært nok til at jeg klarte å skjønne dette.

Mulig jeg misforstår deg helt nå, men er `expr` spørringen som sier når alert skal trigges? I så fall er det ikke den som vises i Slack meldingen og som kan fortelle hvilken app det er snakk om. Det er vel feltene "alert", "description" og "action".

**Comment by ahusby** [comment]
Nå har jeg gjort et nytt forsøk på å skjønne dette. Jeg lurer på om vi legger forskjellig betydning i ordet "expr"?

Jeg har brukt som eksempel https://github.com/navikt/finn-kandidat-api/blob/master/nais/alerts.yaml. Ingen av av alertene har en verdi i feltet "expr" som jeg kan kopiere inn i https://prometheus.dev-fss.nais.io/ og som gir et resultat likt det du beskriver.

Men ved å prøve å feile fikk jeg noe fornufting ved å endre på det ene søket:

`up{app="finn-kandidat-api", job="kubernetes-pods"}`
gir meg to slike rader:
`up{app="finn-kandidat-api", instance="192.168.198.13:8080", job="kubernetes-pods", kafka="enabled", kubernetes_namespace="arbeidsgiver", kubernetes_pod_name="finn-kandidat-api-6fb8b9548-xj6rs", pod_template_hash="6fb8b9548", team="arbeidsgiver"}`

Ditt eksempel på spørring `kube_deployment_status_replicas_available == 2`
gir meg
`kube_deployment_status_replicas_available{app_kubernetes_io_instance="nais-kube-state-metrics", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="kube-state-metrics", deployment="finn-kandidat-api", helm_sh_chart="kube-state-metrics-3.2.0", instance="192.168.166.17:8080", job="kubernetes-service-endpoints", kubernetes_name="nais-kube-state-metrics", kubernetes_namespace="nais", kubernetes_pod_node_name="b27apvl00500.preprod.local", namespace="arbeidsgiver"}`

Betyr dette at hvilke labels som er tilgengelig i appens alerts-yml-fil i feltene alert, description og action varierer med hva som er spørringen? I så fall betyr det at det ikke finne én label som alltid gir meg navnet på appen min? I de to tilfellene over må jeg enten referer til "app" (øverste ekesempel) eller til "deployment" (nederste eksempel).

Jeg blir litt nervøs for at dette er skjørt, altså sårbart for feil. Jeg får jo ingen tilbakemelding hvis jeg i alerts-yml referer til et felt som ikke finnes. Jeg begynner å tenke at det enkleste tross alt er å ha én alerts-yml-fil per app og å hardkode appnavnet i den. Når vi kopierer alerts-yml til en nylaget app kan vi bare kjøre søk-og-erstatt, som er en enkel operasjon i enhver teksteditor.

**Comment by Kyrremann** [comment]
Helt riktig at forskjellige spørringer gir svar med forskjellige _labels_. Har man behov for å sikre seg at spørringer gir noenlunde like _labels_ så må man lage mer kompliserte spørringer hvor man _join_-er forskjellige spørringer. Slik som man gjør i SQL.

Som alt annet så er det sårbar for menneskelig feil. Vil uansett ikke si at det er enklere å hardkode appnavn og copy/paste alerts-filen rundt. Det du må ha kontroll på er hva spørringen din returnere, og så bruke labels basert på det. Da kan du fint ha en alert-fil for teamet ditt som treffer flere apper samtidig i namespacet ditt.

**Comment by ahusby** [comment]
Nå har det gått et par dager siden jeg skrev forrige melding, som jeg nok skrev mens jeg var litt frustrert. Enig at jeg må ha kontroll hva spørringen returnerer og at den fungere etter hensikten, og det betyr at jeg må teste den ( manuelt). Da hadde det vært best om jeg hadde bare én alert-fil som jeg trengte å teste. Når hver app har hvaer sin kopi er det høy sannsynlighetnfor at "kopiene" ikke er like etter en stund. Jeg tror jeg skal ta meg enda mer tid til å prøve å til én alert-fil med basic alerts for alle appene våre, hvis teamet mitt er ening at det er riktig prioritering (vi har jo egentlig klart oss godt nok hittil uten helt å forstå dette).

Jeg føler at dette er en av de mindre modne delene av Nais-plattformen. Ellers har jeg hatt feil forventninger om hvor lett dette skal være.

**Comment by ahusby** [comment]
Her er en idé til hvordan dokumetasjon kan bli mer i tråd med det jeg hadde behov for da jeg begynte på dette sporet: Lag et eget kapittel i dokumentasjonen som handler om "Hvordan lage en alerts-fil som kan brukes av alle applikasjonene dine".

For det er dette som er det egentlige ønskede utfallet når en utvikler kommet til denne delen av dokumentasjonen? Under en sånn overskrift kan man komme inn på hvorfor det er lurt, og det rent tekniske med hvordan man bruker labels og tester spørringene sine osv.

**Comment by ahusby** [comment]
Jeg opprettet https://github.com/nais/doc/pull/230 som en billig, liten forbedring inntil ev. et slikt nytt kapittel foresltt kommer.

**Comment by Kyrremann** [comment]
Liker idéen din om å ha et eget kapittel om hvordan man kan samle alerts for flere apper i en fil. Også enig om at dette kanskje er litt mer bare-bone enn mye annet i plattformen.

**Comment by ahusby** [comment]
Ok. Hva blir neste skritt? Lukke denne issuen og opprettte en ny for et slikt kapittel? Skal jeg gjøre det?

**Comment by Kyrremann** [comment]
Høres ut som en god idé! Blir det også litt mer ryddig.

**Comment by ahusby** [comment]
Opprettet https://github.com/nais/doc/issues/232
