### ISSUE TITLE
Fikse recommended alerts basert på tilgjengelige metrikker i et naas cluster

### ISSUE THREAD

**Issue by frodesundby** [nais/doc#297]
Docen anbefaler å lage alerts på metrikker som ikke eksisterer i nginx.
Vi bør derfor se over hvilke alerts vi anbefaler slik at kart stemmer med terreng.

https://doc.nais.io/observability/alerts/recommended_alerts/ er per skrivende stund kun mulig å bruke onprem da den bruker metrikker fra traefik

**Comment by jhrv** [comment]
fixed 9884f78
