### ISSUE TITLE
Burde unngå horisontal-scroll i tabeller

### ISSUE THREAD

**Issue by Kyrremann** [nais/doc#31]
https://doc.nais.io/in-depth/nais-manifest har en tabell som er veldig bred. Se på andre løsninger for å vise innholdet.

@ThomasKasene foreslår:
1. Legge Required-kolonnen mellom "Parameter" og "Description" så den ikke "forsvinner". Det er uansett den smaleste kolonnen av alle
2. Dele hele tabellen inn i flere mindre tabeller så man ikke får så lange parameternavn. Á la:
```
Metadata:
Parameter   Required  Description
name        x         ...
```
Må bare sørge for å synliggjøre at `metadata:`  må være med

**Comment by linemos** [comment]
Ang 2.
Enig i at det kan løse mye med å dele opp tabellen i mindre tabeller, men hvordan deler vi opp? Sånn?

## Metadata:
| Parameter | Required | Default value | Description |
|---|---|---|---|
| name | x | | Name of app |
| namespace | x | | Namespace of app |
| labels.team | x | |Team label |

## Spec
| Parameter | Required | Default value | Description |
|---|---|---|---|
| image | x | | Image |
| port | x | | port |
| spec.strategy.type |  | RollingUpdate | strategy type |

**Comment by ThomasKasene** [comment]
Jeg er litt redd for at `metadata: ` og `spec: ` forsvinner litt i formateringen her. Det er viktig at de feltene også kommer frem av dokumentasjonen. En mulighet er å bite i det sure eplet og droppe tabeller og heller bruke headers og TOC for å organisere:

Table of Contents:
- metadata
  - name
  - namespace
  - labels
    - team
- spec
  - image
  - port
  - strategy
    - type

## metadata
Key: `metadata`
Description: ...

### name
Key: `metadata.name`
Required: `true`
Default value: ...
Description: Name of app

### namespace
Key: `metadata.namespace`
Required: `true`
Default value: `default`
Description: Namespace of app

Alternativt kan man jo forsøke en mer flat struktur der undertittelen er key'en, for å være litt mer minimalistisk. Noe á la:

## `metadata`
Key: `metadata`
Description: ...

## `metadata.name`
Required: `true`
Default value: ...
Description: Name of app

## `metadata.namespace`
Required: `true`
Default value: `default`
Description: Namespace of app

**Comment by Kyrremann** [comment]
Ta gjerne en titt på denne: https://doc.nais.io/v/prettier_spec/observability/alerts/spec#metadata

**Comment by Kyrremann** [comment]
Denne er nå løst, vi endte opp med å gå for en kombinasjon av det som er forslått her
