### ISSUE TITLE
Eksempel på kommando for å gi meg selv insert rettighet til Postgres

### ISSUE THREAD

**Issue by ahusby** [nais/doc#371]
Jeg fant https://doc.nais.io/cli/commands/postgres/#users-add  men jeg klarer ikke å forfatte en kommando som gir meg rettigheter til å kjøre en insert i Postgres tabellen min (som jeg kan kjøre select på). Et eksempel på en slikkommando i dokumentasjonen hadde vært gull.

**Comment by Kyrremann** [comment]
Her kunne vi listet opp eller lenket til Postgres sin dokumentasjon om `privileges`, så det er lettere å skjønne hva slags muligheter man har her.
https://www.postgresql.org/docs/current/ddl-priv.html

**Comment by jhrv** [comment]
@mortenlj ?

**Comment by mortenlj** [comment]
Jeg skal ærlig innrømme at jeg vet ikke helt hva som er riktig svar, så klarer ikke hoste opp en kommando vi kan putte i dokumentasjonen. Jeg tror også dette kan være litt relatert til nais/cli#274, så kan være vi kan se på det hvis/når vi tar tak i den ...

**Comment by Kyrremann** [comment]
Lukker denne, da dette er et problem man må løse i sin egen database-kode. Da vi ikke har lagt opp til at cliet skal inn og endre rettigheter på tabeller som finnes.
