### ISSUE TITLE
Informasjon om Docker

### ISSUE THREAD

**Issue by Kyrremann** [nais/doc#38]
Docker er en vital del av alles hverdag, men ikke nevnt i stor grad i dokumentasjonen vår. Finne et passende sted å dokumentere bruken vår av Docker, og lenke til relevant dokumentasjon. Kan også nevne at det er fullt mulig å bruke noe annet enn Docker, så lenge man kan tilby et Docker-image.

**Comment by x10an14** [comment]
Follow-up in https://github.com/navikt/utvikling/issues/140.
