### ISSUE TITLE
Forklare konseptet med k8s ressurser bedre

### ISSUE THREAD

**Issue by Kyrremann** [nais/doc#47]
Dokumentasjonen vår kunne hatt godt av noen tegninger og beskrivelse på hva som skjer når du lager en `application`-ressurs, og hva en sånn ressurs er for noe.

* Tegning som viser hva vi oppretter
* Hvordan fungerer team, og hvordan bytter en app et team
* Hva er et "miljø", NAIS har ikke miljø, kun cluster og namespace
* Hva er en ressurs, hva er en deploy, deployment (ressurs), en app, application (ressurs)

**Comment by ThomasKasene** [comment]
Et scenario som jeg tror vi kommer til å touche noen ganger fremover:

App A har tilhørt Team T, men så skal Team T splittes opp til Team U og Team V, og App A skal flyttes til Team V.
Problemet er at App A finnes i flere namespaces (kanskje u1 og default) og både dev-fss og prod-fss, og appen er mye brukt av konsumenter både i dev-fss og i prod-fss.

Hvordan løser man dette med minimalt (helst ingen) nedetid for konsumenter?

**Comment by VegarM** [comment]
> Hvordan løser man dette med minimalt (helst ingen) nedetid for konsumenter?

En utvikler som er medlem i Team T og Team V kan endre team label på `Application` ressursen til App A med 0 nedetid.

**Comment by VegarM** [comment]
Tenker vi ikke bør dokumentere ting som allerede er dokumentert bedre av andre (Deployment), men heller henvise til den offisielle dokumentasjonen.

**Comment by Kyrremann** [comment]
> Tenker vi ikke bør dokumentere ting som allerede er dokumentert bedre av andre (Deployment), men heller henvise til den offisielle dokumentasjonen.

Enig med deg der, men tenker det er viktig å nevne hva det er, og så lenke til hvor man kan finner mer dokumentasjon. For jeg tro det å si at vi har en egen k8s ressurs, og så lenke til k8s sin dokumentasjon for ressurser ikke har fungert.

**Comment by stianlaa** [comment]
Jeg tror at team eierskap for applications og pods, og forholdet deres til cluster vs namespace vs "gamle miljø" for mange utviklere er en litt mystisk blackbox som bare fungerer når man fortsetter å deploye slik som før. 

En oppsummerende illustrasjon av hvordan NAIS forholder seg til disse konseptene tror jeg hadde vært veldig nyttig. Du skriver at man kan bytte eierskap på en applikasjon med null nedetid Vegar, men hvilken det var ihvertfall ikke noe jeg fant frem til dokumentasjon om veldig lett.

**Comment by VegarM** [comment]
> En oppsummerende illustrasjon av hvordan NAIS forholder seg til disse konseptene tror jeg hadde vært veldig nyttig. Du skriver at man kan bytte eierskap på en applikasjon med null nedetid Vegar, men hvilken det var ihvertfall ikke noe jeg fant frem til dokumentasjon om veldig lett.

https://doc.nais.io/v/application_change_team_owner/deployment/advanced-usage#change-team-on-already-deployed-application-without-downtime
Da er dette lagt til i docen

**Comment by x10an14** [comment]
Oppdatere denne, nå som ovenfor lenke ikke eksisterer lengre? Har ikke lest igjennom hele doc'en selv ennå, og hittil ikke funnet noe som kunne minne på det.

Hvis det fortsatt eksisterer, refere til det med git-sha referanse og lukke issue?

**Comment by Kyrremann** [comment]
Svaret til Vegar er ikke svar på mitt originale spørsmål, men heller et svar til Thomas sin kommentar. Jeg mente at vi burde forklare mer hva k8s ressurser er, og hvordan de henger sammen (spesielt med application-ressursen). Er flere som har enkle spørsmål om dette, men syns det er for komplisert å bare "lese" k8s dok-en.

**Comment by Kyrremann** [comment]
Føler dette behovet har forsvunnet. Om det er fordi folk har blitt flinkere, eller NAIS har blitt flinkere til å skjule det under 🤷
