### ISSUE TITLE
Samleside for hvor ulike applikasjonsressurser opprettes

### ISSUE THREAD

**Issue by jhrv** [nais/doc#54]
Flere har etterspurt en samleside som innholder linker til dok for hvordan opprette de ulike applikasjonsressursene. 

For eksempel: AAD application, vault, database, servicebrukere etc.

**Comment by Kyrremann** [comment]
Dette er noe som kanskje burde ligge under https://github.com/navikt/utvikling ?

**Comment by jhrv** [comment]
Tenker man kan bruke noe herifra, men at vi bør samle/kurere det litt. Syns fremdeles en samleside gir mening. /cc @linemos
