### ISSUE TITLE
Savner doc av gyldige verdier i alerts config for 'severity' og 'for'

### ISSUE THREAD

**Issue by ahusby** [nais/doc#56]
Skulle ønske dokumentasjonen på https://doc.nais.io/observability/alerts/spec#spec-alerts inneholdt de gyldige verdiene jeg kan bruke for spec.alerts[].severity og spec.alerts[].for

(Forøvrig er navnet "for" ikke så beskrivende. Hva med "wait" eller "endure" eller "tolerate", ev. postfixet med "-duration"? Jeg kan leve med det som det er, det koster sikkert mer enn det smaker å endre på.)

**Comment by ahusby** [comment]
Fra feilmelding fra kubectl ved forsøk på opprette alerts:
spec.alerts.severity in body should match 'good|warning|danger|#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})'

Hva er "#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})"?

**Comment by linemos** [comment]
Spec-formatet vårt har i dag ikke tatt høyde for å liste gyldige verdier. Er dette et greit format?

```
### spec.alerts[].severity
Alert level for Slack messages.

**Default:** danger
**Allowed values:** good|warning|danger
```

**Comment by ahusby** [comment]
@linemos Ja, det er veldig greit, synes jeg, for severity. Hvordan vil det se ut for `spec.alerts[].for`?

**Comment by linemos** [comment]
### spec.alerts[].for
Duration before the alert should trigger.

**Required:**  true
**Allowed values:** '^\d+[smhdwy]$' // her har jeg ikke noe bedre forslag på stående for enn å paste regexen...

**Comment by linemos** [comment]
> Hva er "#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})"?

Det er en fargekode for slack-meldinga. Her må vi dokumentere bedre. https://doc.nais.io/observability/alerts#slack-here-and-team

**Comment by ahusby** [comment]
> her har jeg ikke noe bedre forslag på stående for enn å paste regexen...
Foreslår et par forskjellige eksempler med tilhørende forklaring i tillegg til regexen

**Comment by linemos** [comment]
Hvordan ser dette ut? https://github.com/nais/doc/blob/allowed-values-spec/observability/alerts/spec.md#specalertsfor

**Comment by ahusby** [comment]
Bra. Men altenativene for uke og år er vel så lite aktuelt å bruke at det burde være ugyldig input (og gitt valideringsfeil)?

**Comment by linemos** [comment]
> Men altenativene for uke og år er vel så lite aktuelt å bruke at det burde være ugyldig input (og gitt valideringsfeil)?

Dette tenker jeg vi tillater som input.

**Comment by linemos** [comment]
Lagt til gyldige formater og eksempler i #64
