### ISSUE TITLE
Logging: Mangler informasjon om "x_" prefix

### ISSUE THREAD

**Issue by erik-a-e** [nais/doc#570]
Om man søker etter `x_` i søkefeltet, så dukker det ikke opp noe relevant dokumentasjon.

Ref logging, og at dette er et prefix som settes på "ikke-gjenkjente" felter.

**Comment by jhrv** [comment]
@Starefossen @terjesannum ?

**Comment by Kyrremann** [comment]
Ser ut til å være løst med tagging-jobben og generell utvikling som er gjort den siste tiden!
https://docs.nais.io/workloads/reference/ingress/?h=x_#log-fields-description
