### ISSUE TITLE
Ønsker eksempel på alert "høy feilrate for http-requester" for Tomcat

### ISSUE THREAD

**Issue by ahusby** [nais/doc#59]
I anbefalte alerts i https://github.com/nais/doc/blob/master/observability/alerts/recommended_alerts.md er det en alert "høy feilrate for http-requester". Den bruker Jetty. Default for Spring Boot er Tomcat. Ønsker meg et eksempel på hvordan jeg får samme alert for Tomcat. Fordi jeg sliter skikkelig med å finne det ut selv.

**Comment by Kyrremann** [comment]
Ser du også startet en tråd på Slack, ville bare si at `recommended_alerts.md` er skrevet/basert på hva utviklerne bruker. Så vi/jeg (i hvert fall) har ingen direkte tips til et sånt eksempel.

PS: Kom gjerne med forslag basert på hva dere fant ut på slack.

**Comment by ahusby** [comment]
Jeg skal lage en pull-request så snart jeg har PromQL-spørring klar for min app.

**Comment by ahusby** [comment]
@Kyrremann https://github.com/nais/doc/pull/60

**Comment by linemos** [comment]
Kan denne lukkes da?
