### ISSUE TITLE
Alerts: Skal Slack-kanaler angis med eller uten #-tegnet?

### ISSUE THREAD

**Issue by ahusby** [nais/doc#84]
Det står ikke noe om det her https://doc.nais.io/observability/alerts/spec#spec-receivers-slack-channel
og nå som vi sliter med at vi ikke får alerts fra vår nye app leter vi med lys og lykter etter hva som kan være feil.

**Comment by Kyrremann** [comment]
Spiller ingen rolle: https://github.com/nais/alerterator/blob/master/api/receivers/receivers.go#L59

Tenker du det er kjekt å si det eksplisitt?

**Comment by ahusby** [comment]
Ja, for da hadde jeg sluppet å tenke på om dette var en feil hos meg, når jeg ser at det er annereledes i andre apper.
