### ISSUE TITLE
Burde navnet "clusters" forbli som det står i doc'en?

### ISSUE THREAD

**Issue by x10an14** [nais/doc#99]
Heisann,

Jeg er jo nyansatt her, og har brukt anledningen til å gå over dokumentasjonen med "ferske øyne".

Spørsmålet jeg kunne ønske meg å drøfte med resten er om jeg har gått glipp av noe resonnement/tankegang bak hvorfor å kalle den ene seksjonen for `clusters`?
* Jeg ser selvfølgelig at mappenavnet heter det
* Men føler at seksjonen dreier seg egentlig om å beskrive argumentasjoner/fremgangsmåte for å flytte _applikasjoner_ til GCP

Inputs, noen?

**Comment by jhrv** [comment]
Denne seksjonen er tiltenkt "tjenesten" kjøretidsmiljø som vi leverer. Kunne nok vært navnet annerledes, f.eks noe med kubernetes eller runtime environment eller noe i den duren. Migrering er en midlertidig subseksjon her.

**Comment by x10an14** [comment]
Jeg kommer jo med "nye øyne" uten assosiasjoner og referanser de som har jobbet i NAV en stund sitter inne med.
Er det da noe vits i å diskutere videre om det skal re-names/endres? Er jo en litt større jobb.

Hvis jeg tolker din input korrekt, så er det kanskje ikke verdt det i og med at det skal være midlertidig, og kanskje er noe utelukkende "nye folk" kan slite med.

**Comment by jhrv** [comment]
Hadde kanskje hjulpet å ha en litt mer beskrivende tekst her https://doc.nais.io/clusters , som forklarer ca det jeg sa lenger opp.

**Comment by x10an14** [comment]
Gammel: https://doc.nais.io/clusters
Ny: https://doc.nais.io/v/clarify-clusters-section-name/clusters (ref. PR https://github.com/nais/doc/pull/100)

Ok? =)

**Comment by Kyrremann** [comment]
Er denne nå løst?

**Comment by x10an14** [comment]
Jupp!
